### ISSUE TITLE
Research: Initial Setup for Project Alfred

### ISSUE THREAD

**Issue by the-codefactory-dev** [hack-of-all-codes/project-tradebutler#12]
Refer to the initial [architecture](../blob/master/ARCHITECTURE.md).
After this, implement [DEVOPS-0002](2)

Figure out the initial spring configuration that we need for a [spring boot microservice](https://start.spring.io/).

**Comment by the-codefactory-dev** [comment]
# Boot Version: 2.0.0
### Legend:
** - probably wont need for now

### Core:
Security**
[AOP](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/aop.html)**
[Cache](https://spring.io/guides/gs/caching/)**
[DevTools](http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html): Automatic Restart, Remote Debug (Opt In if really needed)
Session**: in case we need a shared security session
[Lombok](https://projectlombok.org/index.html): [Value](https://projectlombok.org/features/Value.html), [Data](https://projectlombok.org/features/Data.html), [NonNull](https://projectlombok.org/features/NonNull.html), [SneakyThrows](https://projectlombok.org/features/SneakyThrows.html), [Log](https://projectlombok.org/features/Log.html)

### Web:
[Data-REST Repositories](http://docs.spring.io/spring-data/rest/docs/3.0.0.M1/reference/html/#install-chapter)
[HATEOS](http://docs.spring.io/spring-data/rest/docs/3.0.0.M1/reference/html/#install-chapter): Comes with Data but might come in handy if i want to expose some things
HAL Browser
REST Docs: [YouTube](https://www.youtube.com/watch?v=iWj-t69EdN4): REST API Test as Documentation 
[Config Client](https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html)**

### SQL:
PostgreSQL
[Liquibase](http://www.liquibase.org/documentation/spring.html)

### NoSQL:
[REDIS](http://projects.spring.io/spring-data-redis/)**: not for now, probably when we start optimizing the data cache (or spring security shared session?)

### I/O:
Integration
Kafka**: [YouTube:Spring](https://www.youtube.com/watch?v=wo-aZ3ITLYU)

### Ops:
[Actuator](https://spring.io/guides/gs/actuator-service/)

**Comment by hack-of-all-codes** [comment]
Things to Do After Setting Up:

1. create a README
2. basic end-to-end crud
3. unit tests demo
4. integration tests demo
